### ISSUE TITLE
Link to Synthetix.exchange in Trade view not working

### ISSUE THREAD

**Issue by justinjmoses** [Synthetixio/synthetix-mintr#47]
This button doesn't redirect. Preferably it should be a `anchor` as it's more semantically correct and provides the user with the link's contents when they hover. 

![image](https://user-images.githubusercontent.com/799038/68227860-67b27e00-ffc2-11e9-854f-ab1e400c2190.png)

**Comment by clementbalestrat** [comment]
Thanks @justinjmoses. Just fixed it.
