### ISSUE TITLE
Show Total sUSD and SNX rewards claimed

### ISSUE THREAD

**Issue by hav-noms** [Synthetixio/synthetix-mintr#68]
![image](https://user-images.githubusercontent.com/1251099/68643224-dfede600-0564-11ea-97b8-60f9500a9267.png)

**Comment by bachstatter** [comment]
Do we just the total for the current page? 

Should we show a total for all transactions?

**Comment by clementbalestrat** [comment]
Right. Maybe @hav-noms wanted the total of sUSD in the table but I don't think we should had it as sUSD is not escrowed.

**Comment by clementbalestrat** [comment]
Closing this one
