### ISSUE TITLE
Logging in with trezor is broken on prod

### ISSUE THREAD

**Issue by bachstatter** [Synthetixio/synthetix-mintr#96]
![image](https://user-images.githubusercontent.com/5688912/69501854-1e1fd800-0f5d-11ea-82c3-6aea2b3b7e08.png)

**Comment by clementbalestrat** [comment]
Are you sure you're not on Kovan?

**Comment by bachstatter** [comment]
I was, didn't realize that the network I picked in metamask could affect trezor login

**Comment by clementbalestrat** [comment]
It affects the network yes

**Comment by bachstatter** [comment]
Cool!
